### ISSUE TITLE
Trouble opening apps from the launcher

### ISSUE THREAD

**Issue by Pablo-Caballero-Maria** [pop-os/cosmic-epoch#1016]
Since I upgraded to the alpha 2 of cosmic, when I press `Super` to open the app launcher, and begin to type the name, sometimes it is "frozen" and doesn't list the apps below. And when it does, clicking on one sometimes doesn't open it.

**Comment by maxtremblay** [comment]
I have the same issue. It seems related to the following error.


```bash
Error getting config: com.system76.CosmicAppList [GetKey("enable_drag_source", Os { code: 2, kind: NotFound, message: "No such file or directory" })]

thread 'main' panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
user-provided comparison function does not correctly implement a total order
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by alex100306** [comment]
I am having the same issue on arch. The cosmic-greeter issue apparently is an arch packaging issue, but I'm not sure about the launcher.

**Comment by BVildljung** [comment]
Same problem with the launcher here. On Fedora 40.

**Comment by Mome** [comment]
I am still having the same problem on arch, when starting COSMIC through GDM:

> 
> Dec 12 14:10:15 seraphim cosmic-session[1658]: thread 'main' panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
> Dec 12 14:10:15 seraphim cosmic-session[1658]: user-provided comparison function does not correctly implement a total order
> Dec 12 14:10:15 seraphim /usr/lib/gdm-wayland-session[1658]: 2024-12-12T13:10:15.097813Z  WARN cosmic-launcher: cosmic_session: thread 'main' panicked at library/core/src/slice/sort/shared/smallsort.rs:862:5:
> Dec 12 14:10:15 seraphim /usr/lib/gdm-wayland-session[1658]: 2024-12-12T13:10:15.097840Z  WARN cosmic-launcher: cosmic_session: user-provided comparison function does not correctly implement a total order
> Dec 12 14:10:15 seraphim /usr/lib/gdm-wayland-session[1658]: 2024-12-12T13:10:15.097854Z  WARN cosmic-launcher: cosmic_session: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Dec 12 14:10:15 seraphim cosmic-session[1658]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Dec 12 14:10:15 seraphim systemd-coredump[6551]: Process 6504 (pop-launcher) of user 1000 terminated abnormally with signal 6/ABRT, processing...
> Dec 12 14:10:15 seraphim systemd[1]: Started Process Core Dump (PID 6551/UID 0).
> Dec 12 14:10:16 seraphim systemd-coredump[6552]: [🡕] Process 6504 (pop-launcher) of user 1000 dumped core.
> 
>                                                  Stack trace of thread 6504:
>                                                  #0  0x0000757f006e63f4 n/a (libc.so.6 + 0x963f4)
>                                                  #1  0x0000757f0068d120 raise (libc.so.6 + 0x3d120)
>                                                  #2  0x0000757f006744c3 abort (libc.so.6 + 0x244c3)
>                                                  #3  0x0000631b0a24674a n/a (n/a + 0x0)
>                                                  #4  0x0000631b0a609429 n/a (n/a + 0x0)
>                                                  #5  0x0000631b0a609176 n/a (n/a + 0x0)
>                                                  #6  0x0000631b0a608df3 n/a (n/a + 0x0)
>                                                  #7  0x0000631b0a607cb9 n/a (n/a + 0x0)
>                                                  #8  0x0000631b0a608ab4 n/a (n/a + 0x0)
>                                                  #9  0x0000631b0a1f5ac3 n/a (n/a + 0x0)
>                                                  #10 0x0000631b0a1f991b n/a (n/a + 0x0)
>                                                  #11 0x0000631b0a2c9739 n/a (n/a + 0x0)
>                                                  #12 0x0000631b0a345834 n/a (n/a + 0x0)
>                                                  #13 0x0000631b0a345b84 n/a (n/a + 0x0)
>                                                  #14 0x0000631b0a3457d9 n/a (n/a + 0x0)
>                                                  #15 0x0000631b0a33c825 n/a (n/a + 0x0)
>                                                  #16 0x0000631b0a374e1e n/a (n/a + 0x0)
>                                                  #17 0x0000631b0a256c4a n/a (n/a + 0x0)
>                                                  #18 0x0000631b0a2509ff n/a (n/a + 0x0)
>                                                  #19 0x0000631b0a2df998 n/a (n/a + 0x0)
>                                                  #20 0x0000631b0a2b1603 n/a (n/a + 0x0)
>                                                  #21 0x0000631b0a263f3b n/a (n/a + 0x0)
>                                                  #22 0x0000631b0a2fad0f n/a (n/a + 0x0)
>                                                  #23 0x0000631b0a2e75ff n/a (n/a + 0x0)
>                                                  #24 0x0000631b0a2fa2ec n/a (n/a + 0x0)
>                                                  #25 0x0000631b0a3007b6 n/a (n/a + 0x0)
>                                                  #26 0x0000631b0a33a906 n/a (n/a + 0x0)
>                                                  #27 0x0000631b0a38f5fc n/a (n/a + 0x0)
>                                                  #28 0x0000631b0a5fc615 n/a (n/a + 0x0)
>                                                  #29 0x0000631b0a3009c4 n/a (n/a + 0x0)
>                                                  #30 0x0000757f00675e08 n/a (libc.so.6 + 0x25e08)
>                                                  #31 0x0000757f00675ecc __libc_start_main (libc.so.6 + 0x25ecc)
>                                                  #32 0x0000631b0a192065 n/a (n/a + 0x0)
>                                                  ELF object binary architecture: AMD x86-64
> Dec 12 14:10:16 seraphim systemd[1]: systemd-coredump@2-6551-0.service: Deactivated successfully.
> Dec 12 14:10:16 seraphim systemd[1]: systemd-coredump@2-6551-0.service: Consumed 1.499s CPU time, 1G memory peak.

**Comment by jokeyrhyme** [comment]
@Mome the Arch Linux issue is because the pop-launcher package is out of date, and the maintainer hasn't updated it to the version with the fix in it

**Comment by iamkartiknayak** [comment]
Does it still happen?

**Comment by maxtremblay** [comment]
I don't have the issue anymore

**Comment by leviport** [comment]
We can reopen this later if needed.

**Comment by patrulhasirius** [comment]
I still have this issue in a fresh updated arch install, only open apps appear on the launcher.

**Comment by iamkartiknayak** [comment]
Is launcher the latest build? I heard from somone that chaotic aur is best as it maintains latest packages for cosmic

**Comment by patrulhasirius** [comment]
I tried both the aur and official arch packages, same result.
