### ISSUE TITLE
Polkit not working: cosmic alpha 2

### ISSUE THREAD

**Issue by AngryPenguinPL** [pop-os/cosmic-epoch#1065]
I'm trying to compile COSMIC for my distribution, I have a generally working desktop but I noticed that applications that require polkit to run like yumex or dnfdragora don't allow installing packages due to an authentication problem.

So my question is, what in COSMIC is responsible for the polkit service?

Same story with cosmic-store:
![1727969023141](https://github.com/user-attachments/assets/30f1521a-e1dd-48a9-8d90-d71f136795ab)

I see this when app trying perform opration that need polkit:
```
Oct 03 15:00:57 omv-3382 cosmic-session[1242]: called `Option::unwrap()` on a `None` value
Oct 03 15:02:28 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 25 > 19)
Oct 03 15:02:28 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 25 > 19)
Oct 03 15:02:28 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 25 > 19)
Oct 03 15:03:53 omv-3382 cosmic-session[1242]: [2024-10-03T14:03:53Z ERROR cosmic_osd::subscriptions::polkit_agent_helper] creating polkit agent helper: No such file or directory (os error 2)
Oct 03 15:03:53 omv-3382 cosmic-session[1242]: thread 'tokio-runtime-worker' panicked at src/subscriptions/polkit_agent_helper.rs:39:46:
Oct 03 15:03:53 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:03:53.089577Z  WARN cosmic-osd: cosmic_session: [2024-10-03T14:03:53Z ERROR cosmic_osd::subscriptions::polkit_agent_helper] creating polkit agent helper: No such file or directory (os error 2)
Oct 03 15:03:53 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:03:53.089598Z  WARN cosmic-osd: cosmic_session: thread 'tokio-runtime-worker' panicked at src/subscriptions/polkit_agent_helper.rs:39:46:
Oct 03 15:03:53 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:03:53.089608Z  WARN cosmic-osd: cosmic_session: called `Option::unwrap()` on a `None` value
Oct 03 15:03:53 omv-3382 cosmic-session[1242]: called `Option::unwrap()` on a `None` value
Oct 03 15:04:09 omv-3382 cosmic-session[1242]: [2024-10-03T14:04:09Z ERROR cosmic_osd::subscriptions::polkit_agent_helper] creating polkit agent helper: No such file or directory (os error 2)
Oct 03 15:04:09 omv-3382 cosmic-session[1242]: thread 'tokio-runtime-worker' panicked at src/subscriptions/polkit_agent_helper.rs:39:46:
Oct 03 15:04:09 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:04:09.470601Z  WARN cosmic-osd: cosmic_session: [2024-10-03T14:04:09Z ERROR cosmic_osd::subscriptions::polkit_agent_helper] creating polkit agent helper: No such file or directory (os error 2)
Oct 03 15:04:09 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:04:09.470638Z  WARN cosmic-osd: cosmic_session: thread 'tokio-runtime-worker' panicked at src/subscriptions/polkit_agent_helper.rs:39:46:
Oct 03 15:04:09 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:04:09.470658Z  WARN cosmic-osd: cosmic_session: called `Option::unwrap()` on a `None` value
Oct 03 15:04:09 omv-3382 cosmic-session[1242]: called `Option::unwrap()` on a `None` value
Oct 03 15:07:37 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 25 > 12)
Oct 03 15:07:37 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 25 > 12)
Oct 03 15:07:37 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 25 > 12)
Oct 03 15:07:43 omv-3382 su[14220]: pam_unix(su:session): session closed for user root
Oct 03 15:08:00 omv-3382 sudo[16657]:     live : HOST=omv-3382 ; TTY=pts/0 ; PWD=/home/live ; USER=root ; COMMAND=/usr/sbin/journalctl -b
Oct 03 15:08:03 omv-3382 systemd[1191]: app-cosmic-com.system76.CosmicAppList-16662.scope: Couldn't move process 16662 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-cosmic-com.system76.CosmicAppList-16662.scope': No such process
Oct 03 15:08:03 omv-3382 systemd[1191]: app-cosmic-com.system76.CosmicAppList-16662.scope: Failed to add PIDs to scope's control group: No such process
Oct 03 15:08:03 omv-3382 systemd[1191]: app-cosmic-com.system76.CosmicAppList-16662.scope: Failed with result 'resources'.
Oct 03 15:08:03 omv-3382 systemd[1191]: Failed to start app-cosmic-com.system76.CosmicAppList-16662.scope - Application launched by COSMIC.
Oct 03 15:09:11 omv-3382 systemd[1191]: app-cosmic-com.system76.CosmicAppList-15624.scope: Consumed 4min 6.406s CPU time, 827.9M memory peak.
Oct 03 15:09:21 omv-3382 systemd[1191]: Started app-cosmic-com.system76.CosmicAppList-17631.scope - Application launched by COSMIC.
Oct 03 15:09:29 omv-3382 cosmic-comp[1273]: [GL] GL_INVALID_VALUE in glTexSubImage2D(xoffset 0 + width 19 > 12)
​
```

I should add that I have tried installing other polkits like:
```
rpm -qa|grep polkit
lib64polkit-gobject1_0-125-1.x86_64
lib64polkit-agent1_0-125-1.x86_64
lib64polkit-qt6-core-1_1-0.114.1-0.20230513.1.x86_64
lib64polkit-qt5-core-1_1-0.114.0-1.x86_64
polkit-125-1.x86_64
systemd-polkit-256.6-1.x86_64
polkit-gnome-0.105-14.x86_64
lib64polkit-gir1.0-125-1.x86_64
lib64polkitagent-gir1.0-125-1.x86_64
```

Here is full journalctl log: 
https://dpaste.org/gfKer

**Comment by jokeyrhyme** [comment]
I think the responsibility is over in cosmic-osd

https://github.com/pop-os/cosmic-osd/blob/master/src/components/polkit_dialog.rs

**Comment by Drakulix** [comment]
Ping @ids1024

**Comment by ids1024** [comment]
```
Oct 03 15:04:09 omv-3382 cosmic-session[1242]: [2024-10-03T14:04:09Z ERROR cosmic_osd::subscriptions::polkit_agent_helper] creating polkit agent helper: No such file or directory (os error 2)
Oct 03 15:04:09 omv-3382 cosmic-session[1242]: thread 'tokio-runtime-worker' panicked at src/subscriptions/polkit_agent_helper.rs:39:46:
Oct 03 15:04:09 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:04:09.470601Z  WARN cosmic-osd: cosmic_session: [2024-10-03T14:04:09Z ERROR cosmic_osd::subscriptions::polkit_agent_helper] creating polkit agent helper: No such file or directory (os error 2)
Oct 03 15:04:09 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:04:09.470638Z  WARN cosmic-osd: cosmic_session: thread 'tokio-runtime-worker' panicked at src/subscriptions/polkit_agent_helper.rs:39:46:
Oct 03 15:04:09 omv-3382 /usr/libexec/gdm-wayland-session[1242]: 2024-10-03T14:04:09.470658Z  WARN cosmic-osd: cosmic_session: called `Option::unwrap()` on a `None` value
Oct 03 15:04:09 omv-3382 cosmic-session[1242]: called `Option::unwrap()` on a `None` value
```

Looks like it's not finding `/usr/libexec/polkit-agent-helper-1`.  Presumably it's at a different path on that distro (or isn't installed, and needs to be; I presume it's part of the polkit package though).

Cosmic-osd seems to currently have a `polkit-agent-helper-1` variable that can be set with `make`.

**Comment by AngryPenguinPL** [comment]
Yes, looks like in my distro polkit helper is located in /usr/lib/polkit-1/polkit-agent-helper-1. Changing make file to this location fixing it.

Thanks.
