### ISSUE TITLE
[BUG] Searching "sp" in the launcher causes the launcher to exit unexpectedly

### ISSUE THREAD

**Issue by baldemoto** [pop-os/cosmic-epoch#1203]
I discovered this while attempting to open Spotify from the launcher. When I began to search "sp" in the launcher, the launcher crashes, forcing focus back to whichever window I was focused on beforehand. However, searching "Sp" (with an uppercase) does not reproduce this issue, and I can search and open spotify without issue.

**Comment by git-f0x** [comment]
I can't reproduce this on my end. Are there any logs when that happens (`journalctl -e _COMM=cosmic-launcher` or just `journalctl`)?

**Comment by baldemoto** [comment]
I don't see an output from `journalctl -e _COMM=cosmic-launcher`. I do, however, see relevant output from `journalctl` :

```
Nov 01 08:53:34 $USER wpa_supplicant[1575]: wlp5s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-54 noise=9999 txrate=864600
Nov 01 08:53:37 $USER cosmic-session[5168]: thread 'main' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
Nov 01 08:53:37 $USER cosmic-session[5168]: user-provided comparison function does not correctly implement a total order
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.336707Z  WARN cosmic-launcher: cosmic_session: thread 'main' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.337203Z  WARN cosmic-launcher: cosmic_session: user-provided comparison function does not correctly implement a total order
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.337220Z  WARN cosmic-launcher: cosmic_session: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 01 08:53:37 $USER cosmic-session[5168]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 01 08:53:37 $USER cosmic-session[5168]: process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=44 cosmic-launcher ' failed with code 101
Nov 01 08:53:37 $USER cosmic-session[5168]: cosmic-launcher exited with error 101
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.340145Z ERROR launch_pad: process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=44 cosmic-launcher ' failed with code 101
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.340156Z ERROR cosmic_session: cosmic-launcher exited with error 101
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.340190Z  INFO launch_pad: draining stdin receiver before restarting process
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.340196Z  INFO launch_pad: sleeping for 4ms before restarting process cosmic-launcher (restart 1)
Nov 01 08:53:37 $USER cosmic-session[5168]: draining stdin receiver before restarting process
Nov 01 08:53:37 $USER cosmic-session[5168]: sleeping for 4ms before restarting process cosmic-launcher (restart 1)
Nov 01 08:53:37 $USER cosmic-session[5168]: sending 1 fds
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.341366Z  INFO cosmic_session::comp: sending 1 fds
Nov 01 08:53:37 $USER cosmic-session[5168]: restarted process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=41 cosmic-launcher ', now at 2 restarts
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.346214Z  INFO launch_pad: restarted process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=41 cosmic-launcher ', now at 2 restarts
Nov 01 08:53:37 $USER cosmic-session[5168]: Failed to spawn scope for cosmic-launcher. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-launcher.scope was already loaded or has a fragment file.
Nov 01 08:53:37 $USER /usr/libexec/gdm-wayland-session[5168]: 2024-11-01T15:53:37.347906Z  WARN cosmic_session: Failed to spawn scope for cosmic-launcher. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-launcher.scope was already loaded or has a fragm>
Nov 01 08:53:37 $USER wpa_supplicant[1575]: wlp5s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-60 noise=9999 txrate=864600
```

**Comment by git-f0x** [comment]
What version of `cosmic-launcher` do you have?

**Comment by baldemoto** [comment]
The version is `cosmic-desktop-1.0.0~alpha.2^20241031-1.fc41.noarch`.

**Comment by baldemoto** [comment]
The version is `cosmic-launcher-1.0.0~alpha.2^git20241029.6fe20b0-1.fc41.x86_64`.

**Comment by baldemoto** [comment]
I realized I had not updated my COSMIC packages (I thought I had before this). However, after updating it, I am still getting the same error. Here is the relevant `journalctl` output:

```
Nov 01 09:40:17 $USER cosmic-session[2582]: thread 'main' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
Nov 01 09:40:17 $USER cosmic-session[2582]: user-provided comparison function does not correctly implement a total order
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.087316Z  WARN cosmic-launcher: cosmic_session: thread 'main' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.087814Z  WARN cosmic-launcher: cosmic_session: user-provided comparison function does not correctly implement a total order
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.087840Z  WARN cosmic-launcher: cosmic_session: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 01 09:40:17 $USER cosmic-session[2582]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 01 09:40:17 $USER cosmic-session[2582]: process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=41 cosmic-launcher ' failed with code 101
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.094256Z ERROR launch_pad: process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=41 cosmic-launcher ' failed with code 101
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.094297Z ERROR cosmic_session: cosmic-launcher exited with error 101
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.094417Z  INFO launch_pad: draining stdin receiver before restarting process
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.094436Z  INFO launch_pad: sleeping for 48ms before restarting process cosmic-launcher (restart 3)
Nov 01 09:40:17 $USER cosmic-session[2582]: cosmic-launcher exited with error 101
Nov 01 09:40:17 $USER cosmic-session[2582]: draining stdin receiver before restarting process
Nov 01 09:40:17 $USER cosmic-session[2582]: sleeping for 48ms before restarting process cosmic-launcher (restart 3)
Nov 01 09:40:17 $USER cosmic-session[2582]: sending 1 fds
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.096058Z  INFO cosmic_session::comp: sending 1 fds
Nov 01 09:40:17 $USER cosmic-session[2582]: restarted process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=43 cosmic-launcher ', now at 4 restarts
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.144901Z  INFO launch_pad: restarted process ' DISPLAY=:0 WAYLAND_DISPLAY=wayland-1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=43 cosmic-launcher ', now at 4 restarts
Nov 01 09:40:17 $USER cosmic-session[2582]: Failed to spawn scope for cosmic-launcher. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-launcher.scope was already loaded or has a fragment file.
Nov 01 09:40:17 $USER /usr/libexec/gdm-wayland-session[2582]: 2024-11-01T16:40:17.147038Z  WARN cosmic_session: Failed to spawn scope for cosmic-launcher. Creating transient unit failed with org.freedesktop.systemd1.UnitExists: Unit cosmic-launcher.scope was already loaded or has a fragm>
Nov 01 09:40:17 $USER realmd[2253]: quitting realmd service after timeout
Nov 01 09:40:17 $USER realmd[2253]: stopping service
Nov 01 09:40:17 $USER systemd[1]: realmd.service: Deactivated successfully.
Nov 01 09:40:17 $USER audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=realmd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 01 09:40:23 $USER dbus-broker[1387]: A security policy denied :1.115 to send method call /org/freedesktop/NetworkManager/Settings:org.freedesktop.NetworkManager.Settings.LoadConnections to org.freedesktop.NetworkManager.
Nov 01 09:40:24 $USER systemd[1]: pcscd.service: Deactivated successfully.
Nov 01 09:40:24 $USER audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=pcscd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 01 09:40:27 $USER wpa_supplicant[1583]: wlp5s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-59 noise=9999 txrate=65000
Nov 01 09:40:30 $USER chronyd[1438]: Selected source 45.45.184.14 (2.fedora.pool.ntp.org)
```

**Comment by mmstick** [comment]
Sorting issues were fixed a while back. Make sure you have the latest version of pop-launcher. And make sure you don't have a local build installed to `~/.local/bin`

**Comment by baldemoto** [comment]
I'm not using pop-launcher. I'm using a Fedora Atomic system with COSMIC overlaid from ryanabx's COPR repository. I can confirm that all relevant overlaid packages are up-to-date.

**Comment by mmstick** [comment]
Make sure that your distribution has packaged the latest version of pop-launcher. As this issue was fixed in September: https://github.com/pop-os/launcher/pull/241

**Comment by baldemoto** [comment]
My current version is 1.2.3, so this might be the problem. I'll go ahead and close this issue.
