### ISSUE TITLE
[BUG] Panel Disappears

### ISSUE THREAD

**Issue by nevdelap** [pop-os/cosmic-epoch#1210]
It started happening in recent days, and has happened maybe four or five times. I'm on Arch and I update regularly. I updated yesterday.

It has just been that I realise the panel has disappeared, usually because I go to look at the clock, not knowing how long it hasn't been there because all my attention is in VS Code or whatever. Because it isn't urgent enough that logging out and in and having to set up my applications and terminal windows across my workspaces I've been living without it until the end of the day.

Today I did notice that it disappeared from one screen (external monitor) but was still on the other screen (laptop) for some minutes, before it disappeared from that screen.

After it had disappeared cosmic-panel was still running, as per `ps -ef | grep cosmic-panel`. Since it is the weekend I decided I'd look for a workaround to try and get it back. I tried `kill -HUP` and that froze everything, so I'd have had to log out and log in anyway. I tried a `kill -HUP cosmic-comp` which restarted it, amounting to the same thing.

So I don't have anything more useful at the moment other than to report that it is happening, and it had never happened between early August and a few days ago.

**Comment by nevdelap** [comment]
Two later and the panel was still there. I used `cosmic-settings` to move it the left of the screen which worked, then back to the bottom, and now it has disappeared. (So that is different from it just disappearing, but I was testing if it was responding to changes in settings to do with another issue.)

**Comment by CrazyChaoz** [comment]
So idk if it is related, but I got the following log line right around the time it dissapeared.
I _maybe_ tried dragging an applet while it happened.

```
Nov 07 09:15:47 MYDEVICE cosmic-panel[2784]: com.system76.CosmicAppList: Error getting config: com.system76.CosmicAppList [GetKey("enable_drag_source", Os { code: 2, kind: NotFound, message: "No such file or directory" })]
```

**Comment by canadaduane** [comment]
@nevdelap What version of cosmic are you running, particularly `cosmic-panel`? I noticed the error message in your logs:

```cosmic-comp[1095]: thread 'surface-HDMI-A-1' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:780
```

But the last time `src/backend/kms/mod.rs` had a line 780 was quite some time ago (it was refactored and became a smaller file after May [this file state](https://github.com/pop-os/cosmic-comp/blob/4f076e07530db2e9a671edf63c2b51bdaea826c9/src/backend/kms/mod.rs#L780) in May)

The only `unreachable!` code I see in that file is not on line 780 (it's on line 1377) and refers to mirroring two monitors. A call to `unreachable!` would result in the error message you noted above.

**Comment by nevdelap** [comment]
cosmic-panel-git 1.0.0.alpha.3.r12.gd0d7972

I updated yesterday.

**Comment by Sirius902** [comment]
I'm running the [NixOS COSMIC flake](https://github.com/lilyinstarlight/nixos-cosmic) with the following package versions and I'm also experiencing this issue.

<details>

<summary>Packages</summary>

```
❯ nix-store -q --references /var/run/current-system/sw | cut -d'-' -f2- | grep -i cosmic
cosmic-icons-1.0.0-alpha.6-unstable-2025-02-25
cosmic-randr-1.0.0-alpha.6-unstable-2025-02-20
cosmic-settings-1.0.0-alpha.6-unstable-2025-03-17
cosmic-comp-1.0.0-alpha.6-unstable-2025-03-17
cosmic-applibrary-1.0.0-alpha.6-unstable-2025-03-18
xdg-desktop-portal-cosmic-1.0.0-alpha.6-unstable-2025-03-17
cosmic-settings-daemon-1.0.0-alpha.6-unstable-2025-02-28
cosmic-edit-1.0.0-alpha.6-unstable-2025-03-09
cosmic-bg-1.0.0-alpha.6-unstable-2025-02-05
cosmic-wallpapers-1.0.0-alpha.6-unstable-2024-10-31
cosmic-greeter-1.0.0-alpha.6-unstable-2025-03-15
cosmic-term-1.0.0-alpha.6-unstable-2025-03-13
cosmic-files-1.0.0-alpha.6-unstable-2025-03-13
cosmic-screenshot-1.0.0-alpha.6-unstable-2025-01-14
cosmic-player-1.0.0-alpha.6-unstable-2025-03-13
cosmic-notifications-1.0.0-alpha.6-unstable-2025-03-09
cosmic-session-1.0.0-alpha.6-unstable-2025-02-28
cosmic-applets-1.0.0-alpha.6-unstable-2025-03-18
cosmic-workspaces-epoch-1.0.0-alpha.6-unstable-2025-03-18
cosmic-panel-1.0.0-alpha.6-unstable-2025-03-18
cosmic-launcher-1.0.0-alpha.6-unstable-2025-03-18
cosmic-osd-1.0.0-alpha.6-unstable-2025-03-09
cosmic-idle-1.0.0-alpha.6-unstable-2025-02-25
```

</details>

```
Mar 25 17:33:13 nixlee .cosmic-panel-wrapped[4218]: [EGL] 0x300d (BAD_SURFACE) eglQuerySurface: EGL_BAD_SURFACE error: In eglQuerySurface: Surface (0xd10da565) must be bound as current
Mar 25 17:33:13 nixlee .cosmic-panel-wrapped[4218]: [EGL] 0x300d (BAD_SURFACE) eglQuerySurface: EGL_BAD_SURFACE error: In eglQuerySurface: Surface (0xd10da565) must be bound as current
Mar 25 17:33:14 nixlee .cosmic-panel-wrapped[4218]: [EGL] 0x300d (BAD_SURFACE) eglQuerySurface: EGL_BAD_SURFACE error: In eglQuerySurface: Surface (0xd10da565) must be bound as current
Mar 25 17:33:14 nixlee .cosmic-comp-wrapped[4160]: thread 'surface-DP-2' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:814
                                                      0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                      1: log_panics::Config::install_panic_hook::{{closure}}
                                                      2: std::panicking::rust_panic_with_hook
                                                      3: std::panicking::begin_panic_handler::{{closure}}
                                                      4: std::sys::backtrace::__rust_end_short_backtrace
                                                      5: rust_begin_unwind
                                                      6: core::panicking::panic_fmt
                                                      7: core::panicking::panic
                                                      8: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                      9: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                     10: cosmic_comp::backend::kms::surface::surface_thread
                                                     11: std::sys::backtrace::__rust_begin_short_backtrace
                                                     12: core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                     13: std::sys::pal::unix::thread::Thread::new::thread_start
                                                     14: start_thread
                                                     15: __GI___clone3
Mar 25 17:33:14 nixlee .cosmic-comp-wrapped[4160]: thread 'surface-DP-1' panicked at 'internal error: entered unreachable code': src/backend/kms/surface/mod.rs:814
                                                      0: <backtrace::capture::Backtrace as core::default::Default>::default
                                                      1: log_panics::Config::install_panic_hook::{{closure}}
                                                      2: std::panicking::rust_panic_with_hook
                                                      3: std::panicking::begin_panic_handler::{{closure}}
                                                      4: std::sys::backtrace::__rust_end_short_backtrace
                                                      5: rust_begin_unwind
                                                      6: core::panicking::panic_fmt
                                                      7: core::panicking::panic
                                                      8: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
                                                      9: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
                                                     10: cosmic_comp::backend::kms::surface::surface_thread
                                                     11: std::sys::backtrace::__rust_begin_short_backtrace
                                                     12: core::ops::function::FnOnce::call_once{{vtable.shim}}
                                                     13: std::sys::pal::unix::thread::Thread::new::thread_start
                                                     14: start_thread
                                                     15: __GI___clone3
```

**Comment by nalladev** [comment]
For me both panel and dock disappears. But only when click on the panel after sometime of not interacting with it (while i'am working on something else and when click on power option on panel to see charge level suddenly both panel and dock disappears never to be seen again until i restart the system).

Should i post this as a separate issue?

**Comment by FiretronP75** [comment]
I'm using Pop!OS LTS and also have an issue with the panel and dock going away and not coming back until restart. It happens pretty regularly, at least once a day since the Pop!OS COSMIC upgrade. Packages are all the defaults for Pop. I'm not sure what might be helpful to upload.

**Comment by Luk9091** [comment]
On my Pop!OS after upgrade cosmic to 1.4.0 panel start disapear when I clicked it. After relog everythink work correctly but first click just after system resetart made the panel disapear.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/baeceafb-718d-43ac-8956-f7a67c81f7bf" />

**Comment by nalladev** [comment]
https://github.com/pop-os/cosmic-panel/issues/663#issuecomment-5177440542

**Comment by giovana-morais** [comment]
+1 here. this started to happen after i updated my system. the panel is there until i click on something. then it disappears until restart.

**Comment by Nicktriez** [comment]
The Panel also disappears on COSMIC 1.6 at times when I click it. I have to restart the session before it comes back.

OS: Pop!_OS 24.04 LTS x86_64
Kernel: Linux 7.0.11-76070011-generic
DE: COSMIC 1.0.0
WM: cosmic-comp (Wayland)
Theme: Yaru [GTK3]
Icons: breeze-dark [Qt], Yaru [GTK3]
Cursor: Adwaita
Terminal: cosmic-term 1.5.0
Terminal Font: Noto Sans Mono (14px)
CPU: AMD Ryzen 7 7800X3D (16) @ 5.02 GHz
GPU 1: NVIDIA GeForce RTX 4070 Ti SUPER [Discrete]
GPU 2: AMD Raphael [Integrated]
Memory: 6.27 GiB / 30.50 GiB (21%)
Swap: 0 B / 20.00 GiB (0%)
Disk (/): 88.07 GiB / 1.78 TiB (5%) - ext4
Disk (/recovery): 3.64 GiB / 3.99 GiB (91%) - vfat
Local IP (eno1): 192.168.0.202/24
Locale: en_US.UTF-8
