### ISSUE TITLE
swap window failed

### ISSUE THREAD

**Issue by xingyaoc-1999** [pop-os/cosmic-epoch#1239]
when I use super+x  and drag selected window to target winow  the cosmic session will restart

**Comment by git-f0x** [comment]
I think <kbd>Super</kbd>+<kbd>X</kbd> is more intended to be used with keyboard shortcuts, but I can reproduce the issue, and the compositor certainly shouldn't crash. Of note is that the compositor only crashes when the window is dropped **_while_** <kbd>Super</kbd>+<kbd>X</kbd> is being held.
Relevant crash logs:
```
Nov 11 16:21:12 pop-os cosmic-comp[13657]: thread 'surface-HDMI-A-3' panicked at 'internal error: entered unreachable code': src/shell/layout/tiling/mod.rs:5348
                                              0: <unknown>
                                              1: <unknown>
                                              2: <unknown>
                                              3: <unknown>
                                              4: <unknown>
                                              5: <unknown>
                                              6: <unknown>
                                              7: <unknown>
                                              8: <unknown>
                                              9: <unknown>
                                             10: <unknown>
                                             11: <unknown>
                                             12: <unknown>
                                             13: <unknown>
                                             14: <unknown>
                                             15: <unknown>
                                             16: <unknown>
                                             17: <unknown>
                                             18: <unknown>
                                             19: <unknown>
Nov 11 16:21:12 pop-os cosmic-comp[13657]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NodeIdNoLongerValid': src/shell/layout/tiling/mod.rs:864
                                              0: <unknown>
                                              1: <unknown>
                                              2: <unknown>
                                              3: <unknown>
                                              4: <unknown>
                                              5: <unknown>
                                              6: <unknown>
                                              7: <unknown>
                                              8: <unknown>
                                              9: <unknown>
                                             10: <unknown>
                                             11: <unknown>
                                             12: <unknown>
                                             13: <unknown>
                                             14: <unknown>
                                             15: <unknown>
                                             16: <unknown>
                                             17: <unknown>
                                             18: <unknown>
                                             19: <unknown>
                                             20: __libc_start_main
                                             21: <unknown>
```

**Comment by zeroishero** [comment]
@xingyaoc-1999 This is same as cosmic-comp#924. I have written fix for that for old version but it needs some refining.

**Comment by Programmer2011bird** [comment]
Same issue here 
distro : arch
display / login manager : ly

**Comment by Programmer2011bird** [comment]
Same issue here 
distro : arch
display / login manager : ly

**Comment by jacobgkau** [comment]
Duplicate of https://github.com/pop-os/cosmic-comp/issues/924. Fixed by https://github.com/pop-os/cosmic-comp/commit/b53eb508a8e795bc22f80d85250f73c33195db9d.
