### ISSUE TITLE
[BUG] Unable to open file picker for some flatpak applications

### ISSUE THREAD

**Issue by A-bnk** [pop-os/cosmic-epoch#1331]
When attempting to use the file picker in certain Flatpak applications, the dialog either doesn't appear at all or briefly flashes and then crashes immediately. The issue appears to be inconsistent across different Flatpak applications. For example, Microsoft Edge works, but only because it uses the older GNOME file explorer instead of cosmic-files. Other applications like Betterbird and Sioyek (PDF reader) don't work at all when trying to open the files. The fact that applications using the older GNOME file picker work properly suggests this might be related to cosmic-files? Are there any workarounds available?

Additional observation: When trying to document this issue using OBS to capture the screen behavior, OBS is unable to show the screen capture as well (no Display to choose from when using PipeWire). Do you think this problem might be related?

Some info:
Pop!_OS jammy 22.04 x86_64
Flatpak 1.14.6

**Comment by A-bnk** [comment]
I get the following error when trying to open the file picker of the pdf reader while xdg-desktop-portal-cosmic is running:

```
[2024-12-08T23:12:03Z WARN  xdg_desktop_portal_cosmic::wayland] Failed to find `PORTAL_WAYLAND_SOCKET`; trying default Wayland display
[2024-12-08T23:12:03Z WARN  wgpu_hal::gles::egl] Re-initializing Gles context due to Wayland window
[2024-12-08T23:12:17Z WARN  sctk_adwaita::buttons] Ignoring unknown button type:
thread 'main' panicked at /build/xdg-desktop-portal-cosmic-zTqq5O/xdg-desktop-portal-cosmic-0.1.0pop1~1733331192~22.04~e7c92a7/vendor/iced_widget/src/container.rs:396:49:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-12-08T23:12:18Z WARN  cosmic_files::tab] failed to calculate directory size of "/home/bnk": Cancelled
[2024-12-08T23:12:18Z ERROR iced_winit::platform_specific::wayland::event_loop] SCTK failed to send Control::AboutToWait. TrySendError { kind: Disconnected }
```

journalctl output:
```
Dec 09 00:01:36 pop-os cosmic-session[1323]: restarted process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=115 PORTAL_WAYLAND_SOCKET=117 /usr/libexec/xdg-desktop-portal-cosmic ', now at 21 restarts
Dec 09 00:01:36 pop-os systemd[1268]: Started xdg-desktop-portal-cosmic.scope.
Dec 09 00:06:53 pop-os cosmic-session[1323]: thread 'main' panicked at /build/xdg-desktop-portal-cosmic-zTqq5O/xdg-desktop-portal-cosmic-0.1.0pop1~1733331192~22.04~e7c92a7/vendor/iced_widget/src/container.rs:396:49:
Dec 09 00:06:53 pop-os cosmic-session[1323]: process ' WAYLAND_DISPLAY=wayland-1 DISPLAY=:1 XDG_SESSION_TYPE=wayland WAYLAND_SOCKET=115 PORTAL_WAYLAND_SOCKET=117 /usr/libexec/xdg-desktop-portal-cosmic ' failed with code 101
Dec 09 00:06:53 pop-os cosmic-session[1323]: /usr/libexec/xdg-desktop-portal-cosmic exited with error 101
Dec 09 00:06:53 pop-os cosmic-session[1323]: sleeping for 14680064ms before restarting process /usr/libexec/xdg-desktop-portal-cosmic (restart 21)
Dec 09 00:06:53 pop-os systemd[1268]: xdg-desktop-portal-cosmic.scope: Consumed 1.160s CPU time.
```

**Comment by sandptel** [comment]
Having the same problem with among all of the comsic applicaitons, probably due to issues with `xdg-desktop-portal-cosmic` 
**cosmic-player:**
`[2025-06-06T14:17:06Z WARN  cosmic_player] failed to open file: open dialog failed`
**cosmic-setttings:**
`  ERROR  dialog response error, why: "open dialog subscription errored\n    cause: open dialog failed\n    cause: A portal frontend implementing `org.freedesktop.portal.FileChooser` was not found"`

**Comment by imxade** [comment]
even when downloading files clicking on "save" does nothing with brave flatpak
