### ISSUE TITLE
Testing Host=virt-manager/libvirt/Fedora40 client=Fedora40 fails to login

### ISSUE THREAD

**Issue by rupert160** [pop-os/cosmic-epoch#443]
I have a fedora40 in fedora40 virtual desktop using libvirt. The install method was
```
sudo sed -i '/SELINUX/s/.*/SELINUX=Permissive/g' /etc/selinux/config
sudo setenforce Permissive
dnf copr enable ryanabx/cosmic-epoch
dnf install cosmic-desktop
```
I have also chosen the gdm3 greeter not the cosmic greeter (as they say it is unstable.
the Machine Emulator is arch="x86_64" machine="pc-q35-8.1" does anybody know what config is required?
Alternatively I'd home to know a virtualisation platform/config that is developers are having success with.

Unfortunately I'm failing to get a desktop, as it crashes constantly the following is the error/warning output from login:
```
Jul 19 20:22:11 fedora40 gdm-password][1684]: gkr-pam: unable to locate daemon control file
Jul 19 20:22:11 fedora40 gdm[1013]: Gdm: on_display_added: assertion 'GDM_IS_REMOTE_DISPLAY (display)' failed
Jul 19 20:22:11 fedora40 gsd-media-keys[1228]: gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
Jul 19 20:22:11 fedora40 gsd-media-keys[1228]: Unable to get default source
Jul 19 20:22:11 fedora40 gsd-media-keys[1228]: Unable to get default sink
Jul 19 20:22:11 fedora40 gnome-shell[1104]: Could not release device '/dev/input/event5' (13,69): GDBus.Error:org.freedesktop.login1.DeviceNotTaken: Device not taken
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: Failed to read config 'workspaces'
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: failed to read local shortcuts config 'system_actions': NoConfigDirectory
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: Key-Binding 'Period' only matched case insensitive for "period"
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: Key-Binding 'Period' only matched case insensitive for "period"
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: Key-Binding 'Comma' only matched case insensitive for "comma"
Jul 19 20:22:11 fedora40 cosmic-comp[1876]: shortcuts custom config error: GetKey("custom", Os { code: 2, kind: NotFound, message: "No such file or directory" })
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: Unable to become drm master, assuming unprivileged mode
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: ignoring requested context priority, EGL_IMG_context_priority not supported
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: Erroneous EGL call didn't set EGLError
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: ignoring requested context priority, EGL_IMG_context_priority not supported
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: ignoring requested context priority, EGL_IMG_context_priority not supported
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: ignoring requested context priority, EGL_IMG_context_priority not supported
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: Preferred format AB30 not available: NoSupportedPlaneFormat
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: Preferred format AR30 not available: NoSupportedPlaneFormat
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: Preferred format AB24 not available: NoSupportedPlaneFormat
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error::NoDevice(DrmNode { dev: 57984, ty: Render })': src/backend/kms/surface/mod.rs:313
                                               0: <unknown>
                                               1: <unknown>
                                               2: <unknown>
                                               3: <unknown>
                                               4: <unknown>
                                               5: <unknown>
                                               6: <unknown>
                                               7: <unknown>
                                               8: <unknown>
                                               9: <unknown>
                                              10: <unknown>
                                              11: <unknown>
                                              12: <unknown>
                                              13: <unknown>
                                              14: <unknown>
                                              15: __libc_start_call_main
                                              16: __libc_start_main_impl
                                              17: <unknown>
Jul 19 20:22:12 fedora40 cosmic-comp[1876]: thread 'surface-Virtual-1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /builddir/build/BUILD/cosmic-comp-0a97147e45c4e893ab354bea78b30eaac1e4e633/vendor/smithay/src/desktop/wayland/layer.rs:69
                                               0: <unknown>
                                               1: <unknown>
                                               2: <unknown>
                                               3: <unknown>
                                               4: <unknown>
                                               5: <unknown>
                                               6: <unknown>
                                               7: <unknown>
                                               8: <unknown>
                                               9: <unknown>
                                              10: <unknown>
                                              11: <unknown>
                                              12: <unknown>
                                              13: <unknown>
                                              14: <unknown>
                                              15: start_thread
                                              16: __GI___clone3
Jul 19 20:22:12 fedora40 cosmic-session[1837]: could not read cache file

```

**Comment by exstntlmsnthrp** [comment]
I'm using qemu/kvm and using the cosmic greeter (which looks great!) and am not having any issues. I thought the main issue was having selinux set to permissive, but you've done that.

**Comment by rupert160** [comment]
I discovered it was an issue with the Video requiring `QXL` option too. It is now working. But should go with installation platform documentation.
