### ISSUE TITLE
Fail to start cosmic desktop

### ISSUE THREAD

**Issue by erik-balfe** [pop-os/cosmic-epoch#456]
I am experiencing errors and crashes after switching to the Cosmic desktop on Fedora Silverblue 40. I used the ublue image for the rebase.

Steps to Reproduce According to the guide here (https://github.com/ublue-os/cosmic) :
1. Run `sudo setenforce 0 && getenforce`
2. Rebase to the ublue image using the following command: 
    `rpm-ostree rebase --reboot ostree-unverified-registry:ghcr.io/ublue-os/cosmic-silverblue:40-amd64
   `
2. Reboot the system.

Observed Behavior:
Upon reboot, the following errors and warnings are logged:

```
2024-07-26T22:54:08.288042Z ERROR cosmic_comp::config: Failed to read config 'workspaces': NoConfigDirectory
2024-07-26T22:54:08.288136Z ERROR cosmic_settings_config: Failed to read local shortcuts config "system_actions": NoConfigDirectory
2024-07-26T22:54:08.288213Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Comma"} only matched case insensitive for "comma"
2024-07-26T22:54:08.288229Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Comma"} only matched case insensitive for "comma"
2024-07-26T22:54:08.288245Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Period"} only matched case insensitive for "period"
2024-07-26T22:54:08.288260Z WARN cosmic_settings_config::shortcuts::ram: Key-binding {"Comma"} only matched case insensitive for "comma"
2024-07-26T22:54:08.288275Z ERROR cosmic_settings_config::shortcuts: Failed to become owner of name "org.cosmic.ConfigDaemon": Unable to acquire bus name: { "name": "org.cosmic.ConfigDaemon", "error": NotFound, message: "No such file or directory" }}
2024-07-26T22:54:08.380925Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.380973Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.384149Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.397825Z WARN [libgbm|backend/egl/context]: Ignoring requested context priority, EGL_IMG_context_priority not supported priority=High
2024-07-26T22:54:08.415073Z WARN cosmic_comp::wayland::compositor: Preferred format ARGB not available: NoSupportedPixelFormat
2024-07-26T22:54:08.415132Z WARN cosmic_comp::wayland::compositor: Preferred format ARGB not available: NoSupportedPixelFormat
2024-07-26T22:54:08.529562Z ERROR panic: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error::NoDevices(DrNode { dev: 57984, ty: Render })': src/backend/kms/surface/mod.rs:313
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: <unknown>
10: <unknown>
11: <unknown>
12: <unknown>
13: <unknown>
14: <unknown>
15: __libc_start_call_main
16: __libc_start_main_impl
17: <unknown>

2024-07-26T22:54:08.529552Z ERROR panic: thread 'surface-Virtual-1' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': /buildir/build/BUILD/cosmic-comp-f44e46fa4493dcacbf656a6cfeb5dbe7dced55c5/vendor/smithay/src/desktop/space/mod.rs:69
0: <unknown>
1: <unknown>
2: <unknown>
3: <unknown>
4: <unknown>
5: <unknown>
6: <unknown>
7: <unknown>
8: <unknown>
9: <unknown>
10: <unknown>
11: <unknown>
12: <unknown>
13: <unknown>
14: <unknown>
15: <unknown>
16: start_thread
17: __clone3
```

I also tried with cosmic-base image with only cosmic desktop installed as i got it.
This was without errors during boot.
And got this after enabling the cosmic-greeter.service:

![image](https://github.com/user-attachments/assets/f572c2a5-e131-4b6d-97f3-17b316c97971)

So the service does not start:
![image](https://github.com/user-attachments/assets/104792db-2628-4ae9-9c7c-e50eeed39c54)

logs for the service:
![image](https://github.com/user-attachments/assets/45c557c1-60bc-4782-a5cc-4458c4625951)

Additional Information:
- I tested the same setup on a brand new Fedora 40 Silverblue installation in a virtual machine and encountered the same errors on boot.
- This leads me to believe the issue is with the Cosmic desktop or incompatibility with hardware rather than the ublue image or my current system state.

System Details:
- Hardware Model: Lenovo ThinkPad X1 Carbon Gen 9
- Memory: 32.0 GiB
- Processor: 11th Gen Intel® Core™ i7-1185G7 × 8
- **Graphics:** Intel® Xe Graphics (TGL GT2)
- **Disk Capacity:** 1.0 TB

**Software Information:**
- **Firmware Version:** N32ET91W (1.67)
- **OS Name:** Fedora Linux 40.20240723.0 (Silverblue)
- **OS Build:** (null)
- **OS Type:** 64-bit
- **GNOME Version:** 46
- **Windowing System:** Wayland
- **Kernel Version:** Linux 6.9.9-200.fc40.x86_64

**Comment by Drakulix** [comment]
`surface-Virtual-1` this is very interesting, are you running some display-link adapter or similar by chance? (If you didn't outright stated your hardware, I would have guessed this is a VM setup.)

**Comment by Drakulix** [comment]
> I tested the same setup on a brand new Fedora 40 Silverblue installation in a virtual machine and encountered the same errors on boot.

Oh you also tested a VM setup, is that where the log comes from or not?

For a VM we currently require the hypervisor to support hardware acceleration for the emulated GPU, otherwise COSMIC won't work.
I would expect your log on a dedicated machine to look at least slightly differently.

**Comment by erik-balfe** [comment]
Yes. That one was in a VM just not to break my laptop system.
On real hardware I switched to unsigned image, then switched to signed one and after last reboot get this when trying to enable greeter service. Is there a way i can fox it now? I can provide some more info if needed. Just do not know what else can make sense here. It is ordinary fedora 40 silver blue and cosmic base image, so nothing Else is even installed here. 

![2024-07-30-22-48-45-108 (1) (1)](https://github.com/user-attachments/assets/8eb139c2-3955-4470-a9a7-54ffdd13b472)

**Comment by Drakulix** [comment]
> greetd: error: configured default session user 'cosmic-greeter' not found

That is your problem. I cannot tell you how to solve it, it pretty much looks like an issue with the `ublue-os:cosmic-base` image, because that should've been set up by the cosmic-greeter package.

**Comment by 616b2f** [comment]
I had the same issue, for me it was an configuration problem, see here how I resolved it: https://github.com/ublue-os/cosmic/issues/48#issuecomment-2267722365

Hope that helps you too.

**Comment by erik-balfe** [comment]
Yeah. This helped me
``` shell
$ grep -E '^greetd:' /usr/etc/passwd | sudo tee -a /etc/passwd
$ grep -E '^cosmic-greeter:' /usr/etc/passwd | sudo tee -a /etc/passwd
$ grep -E '^greetd:' /usr/etc/group | sudo tee -a /etc/group
$ grep -E '^cosmic-greeter:' /usr/etc/group | sudo tee -a /etc/group
```
