### ISSUE TITLE
repoman unusable in default installation

### ISSUE THREAD

**Issue by py-crash** [pop-os/cosmic-epoch#692]
**Distribution (run `cat /etc/os-release`):**
   Pop!_OS 24.04 (Alpha)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
repoman:
  Installed: 2.4.0\~1716233177\~24.04\~83329d2

**Issue/Bug Description:**
Missing dependency in default installation makes `repoman` unusable.

**Steps to reproduce (if you know):**
Running from the terminal shows the following error

```
$ /usr/lib/repoman/repoman.pkexec
Traceback (most recent call last):
  File "/usr/bin/repoman", line 57, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 31, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 26, in <module>
    from .dialog import ErrorDialog
  File "/usr/lib/python3/dist-packages/repoman/dialog.py", line 28, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

**Expected behavior:**
Installing the package `gir1.2-notify-0.7` solves the issue:

```
$ sudo apt install gir1.2-notify-0.7
```

This should be installed as default in the ISO and also should be a dependency for the package:

```
$ apt depends repoman
repoman
  Depends: <python3:any> (>= 3.4~)
    python3:i386
    python3
  Depends: gir1.2-gtk-3.0
  Depends: python3-repolib (>= 2.0)
  Recommends: gir1.2-flatpak-1.0
```

**Other Notes:**

**Comment by leviport** [comment]
I just tried a clean install of the Intel/AMD 24.04 alpha 1 ISO, and I was able to launch Repoman after installing. An `apt policy gir1.2-notify-0.7` shows that the dependency is already installed. Which ISO did you use? Was this after installing updates?

**Comment by leviport** [comment]
Is this only occurring in the live environment? I've recreated it there, but I can't get it to happen post-install. Also, I've confirmed that all deps are installed for Repoman when this occurs. 

I'm also wondering if there's a practical purpose to using Repoman in a live environment? It should probably still launch, of course, but knowing the reason for using Repoman in the live environment could help us determine the priority of this bug.

**Comment by py-crash** [comment]
I did refreshed my install (running the installer again) and run the full updates. The problem was still there. I downloaded the Intel/AMD ISO](https://iso.pop-os.org/24.04/amd64/intel/9/pop-os_24.04_amd64_intel_9.iso) from: https://system76.com/cosmic

**Comment by farhatizakaria** [comment]
Solution:

Install the Required Library
Make sure you have the libnotify library and its Python bindings installed on your system. You can install these with:

sudo apt-get install libnotify-bin python3-gi

You might also need the python3-gi package for Python 3 support.

Install gi.repository.Notify Module
You may also need to install the libnotify development package if it’s not already installed:

sudo apt-get install libnotify-dev

**Comment by py-crash** [comment]
The workarround is on the bug report. it just a bug with missing dependencies on the alpha iso and the repos

**Comment by jacobgkau** [comment]
`gir1.2-notify-0.7` is a dependency of `system76-driver`. That's likely why we're seeing it installed out-of-the-box-- the driver's installed by default on System76 hardware, but not non-System76 computers.
