### ISSUE TITLE
Turning off a display(only one on the system) causes cosmic to lock the system up.

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-epoch#84]
Steps to reproduction: 
Use cosmic with a single monitor turn off the monitor if your listening to anything you should here it stop.(I don't have a second monitor right now so I can test if just turning off one will also cause the issue)
Turn back on the monitor.
Results In a black screen where your only option is to force reboot as you can't switch ttys or kill anything.

Expectations:
Audio/Session to continue as normal when monitor is off and when turning it back on cosmic continues where it left off+any input changes when the monitor was off.

Thanks for taking your time to respond to this and I understand that cosmic is pre-alpha.

**Comment by Drakulix** [comment]
Duplicate of https://github.com/pop-os/cosmic-comp/issues/57

**Comment by Drakulix** [comment]
You can leave the issue open, the two are now linked, so I won't forget to close them both once this is eventually resolved and it increases discoverability.

**Comment by Vixea** [comment]
Also if cosmic shutdown shouldn't that make it go to the session manager(sddm in this case or gdm)when I turn on the display again if thats the case it doesn't happen on sddm.

**Comment by Vixea** [comment]
I should probably retest but I'm pretty sure its been resolved

**Comment by jokeyrhyme** [comment]
I don't seem to be able to use `cosmic-randr disable ...` to accomplish this

How are you turning off your last/only output?

**Comment by Vixea** [comment]
Power button or if you wanna unplug it

**Comment by jokeyrhyme** [comment]
Oh, I've been locking the screen and then turning off the last/only output using its power button (which I guess makes it go into standby, not literally zero-power-consumption) for a while now

I even raised an issue about the tiny nuisance that happens when I turn it back on: https://github.com/pop-os/cosmic-comp/issues/679

**Comment by jokeyrhyme** [comment]
Hmmm, I've noticed in both tagged alphas so far that turning my output back on doesn't seem to work anymore, it can't find a DisplayPort signal

However, I can press my system power button triggering a proper shutdown, and this does wake the output back up for a few seconds during that shutdown process, so (for me) the whole system isn't locked up or frozen

**Comment by jokeyrhyme** [comment]
I'm running alpha 3 now, and I've turned my screen off and then back on again

`cosmic-comp` seems to recover, but the apps that were open are all gone

There's this log entry:

```
cosmic-comp[2832]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:974
```

I think this corresponds to https://github.com/pop-os/cosmic-comp/blob/epoch-1.0.0-alpha.3/src/shell/mod.rs#L974

And there's 

```
cosmic-comp[2832]: thread 'surface-DP-2' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }': src/backend/kms/surface/mod.rs:1124
```

I think this corresponds to https://github.com/pop-os/cosmic-comp/blob/epoch-1.0.0-alpha.3/src/backend/kms/surface/mod.rs#L1124

This might still be a bug in the latest commit: https://github.com/pop-os/cosmic-comp/commit/90883c6ab12533da08a31da338881c38aa773634

I haven't recompiled to double-check this yet

**Comment by hayandev** [comment]
There are too many open issues related to monitor connections, so I’ll add a bit of information to the one that seems closest to my situation.

I am using a single monitor, and it is connected via a DP cable. When the set time passes and cosmic-idle turns off the display, a panic occurs in cosmic-comp. This happens because, with a DP cable, the connection is lost when the display is turned off.

When cosmic-comp shuts down, the cosmic desktop environment restarts, so the computer does not lock. And when cosmic-idle activates again, this situation continues to repeat, meaning the computer never locks, no matter how much time passes.

When I return to my desk, all I see is a blank screen with all my work lost.

**Comment by Drakulix** [comment]
> There are too many open issues related to monitor connections, so I’ll add a bit of information to the one that seems closest to my situation.
> 
> I am using a single monitor, and it is connected via a DP cable. When the set time passes and cosmic-idle turns off the display, a panic occurs in cosmic-comp. This happens because, with a DP cable, the connection is lost when the display is turned off.
> 
> When cosmic-comp shuts down, the cosmic desktop environment restarts, so the computer does not lock. And when cosmic-idle activates again, this situation continues to repeat, meaning the computer never locks, no matter how much time passes.

Probably a duplicate of https://github.com/pop-os/cosmic-comp/issues/906

**Comment by Vixea** [comment]
I'd argue its the duplicate but its posted in the probably better location

**Comment by KodeBarista** [comment]
Has this been fixed yet?

**Comment by leviport** [comment]
I believe this is ready to be closed now
