### ISSUE TITLE
Cosmic-screenshot fails.

### ISSUE THREAD

**Issue by James-Randall-14** [pop-os/cosmic-epoch#887]
Hello,

Immediately after logging in, I am able to use cosmic-screenshot for a period of time, but after a couple of minutes, my screenshot shortcut does nothing.

When I try to run `cosmic-screenshot` from the terminal with a full rust backtrace, I get the following:
```
james @ ~/.c/s/tilde-enhanced/js (master)
↪ cosmic-screenshot                                                                                         18:30:51
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.10"))), reply-serial: 17, body: Signature("s") }))
stack backtrace:
   0:     0x560276ebf105 - <unknown>
   1:     0x560276ee6c6b - <unknown>
   2:     0x560276ebb80f - <unknown>
   3:     0x560276ebeede - <unknown>
   4:     0x560276ec0279 - <unknown>
   5:     0x560276ec001a - <unknown>
   6:     0x560276ec0783 - <unknown>
   7:     0x560276ec0664 - <unknown>
   8:     0x560276ebf5c9 - <unknown>
   9:     0x560276ec0397 - <unknown>
  10:     0x560276ee5133 - <unknown>
  11:     0x560276ee5626 - <unknown>
  12:     0x560276c50855 - <unknown>
  13:     0x560276cf22cb - <unknown>
  14:     0x560276d11553 - <unknown>
  15:     0x560276ceabc1 - <unknown>
  16:     0x560276cfedc0 - <unknown>
  17:     0x560276cc9226 - <unknown>
  18:     0x560276d080fc - <unknown>
  19:     0x560276eb664d - <unknown>
  20:     0x560276cfeea4 - <unknown>
  21:     0x769c2043be08 - <unknown>
  22:     0x769c2043becc - __libc_start_main
  23:     0x560276c0eb65 - <unknown>
  24:                0x0 - <unknown>
```
I have `xdg-desktop-portal`, `xdg-desktop-portal-cosmic`, and`xdg-desktop-portal-wlr` installed.

Thanks!

**Comment by OpenBagTwo** [comment]
This issue isn't confined to just `cosmic-screenshot` for me—neither flameshot nor OBS is able to capture my screen right now.

**Comment by James-Randall-14** [comment]
Tested this earlier this morning, it is also the case for me.

**Comment by BenAuerDev** [comment]
I get the same error as described above

**Comment by nevdelap** [comment]
I have this. It was working but I removed and reinstalled cosmic, on Arch, by removing `cosmic-session-git` and its dependencies and reinstalling it.

```
23:27:48 zen ~ cosmic-screenshot
thread 'main' panicked at src/main.rs:69:10:
failed to send screenshot request: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.11"))), reply-serial: 17, body: Signature("s") }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
23:27:56 zen ~ 101
```

**Comment by James-Randall-14** [comment]
> I was having the same issue. Then I switched to the cosmic-greeter and that fixed it. I was using `exec cosmic-session`.

This fixed it for me. Thanks
